### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by beelux** [nix-community/nixos-images#10]
The two most recent/last builds (Build [#50](https://github.com/nix-community/nixos-images/actions/runs/2403071964) and [#51](https://github.com/nix-community/nixos-images/actions/runs/2441779803)) failed.

Taking the [last 21.11 failure](https://github.com/nix-community/nixos-images/runs/6742460004?check_suite_focus=true#step:4:193) (5 days ago at the time of writing) as an example:
```
++ nixos-generate -o /tmp/tmp.LPqShSC7oN/kexec-bundle-x86_64-linux -c /tmp/tmp.LPqShSC7oN/config.nix -f kexec-bundle -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-21.11.tar.gz
error: cannot coerce a set to a string
       at /nix/store/16z5h9r7rvfaay939qd84ibp1xvb0fsx-nixos-generators-1.6.0/share/nixos-generator/formats/kexec.nix:43:9:
           42|         ${kexec_tarball_self_extract_script} \
           43|         ${config.system.build.kexec_tarball}/tarball/nixos-system-${config.system.build.kexec_tarball.system}.tar.xz \
             |         ^
           44|         > $out
(use '--show-trace' to show detailed location information)
```

I'd like to help, but I'm not very knowledgeable on this topic yet. So I thought the best I could do is open an issue to raise awareness.

**Comment by Mic92** [comment]
cc @Lassulus

**Comment by Lassulus** [comment]
hmm, I guess nixos-generators is incompatible with 21.11. Could it be possible to use the nixos-generators version packaged in 21.11 for the build of the 21.11 image?

**Comment by Mic92** [comment]
We use unstable for building. Do we need 21.11? https://github.com/nix-community/nixos-images/blob/e2aec4ab9d4d9a4d838fd635516c404b897f9d2c/.github/workflows/build.yml#L20
I might actually drop 21.11 and add the new nixos release.

**Comment by Mic92** [comment]
Dropped old channels for now. You can see the current build in: https://github.com/nix-community/nixos-images/actions/runs/2473529184

**Comment by Lassulus** [comment]
well I test the nixos-generators usually against unstable and backport it only if it fixes something. So I would recommend building the stable nixpkgs with the shipped nixos-generators version :)

**Comment by Mic92** [comment]
This is fixed.
