### ISSUE TITLE
Add other architectures (aarch64)

### ISSUE THREAD

**Issue by beelux** [nix-community/nixos-images#11]
Adding aarch64 could, among other things, facilitate NixOS installation where users usually [try to use nixos-infect or build kexecs themselves](https://discourse.nixos.org/t/install-nixos-on-oci-oracle-cloud/19161), as netboot.xyz is sometimes much easier to get running than the other workarounds.
This would result in a more "standard" installation for the user.

Note that this is very much an **enhancement** and not an actual "issue" or bug.

I've looked into it a bit, and if an aarch64 machine is needed, [Docker's Setup QEMU](https://github.com/marketplace/actions/docker-setup-qemu) action could be used.
Some people seem to successfully use it outside of building Docker images(like [aspw](https://github.com/rogerbinns/apsw/blob/master/.github/workflows/build-testpypi.yml) or [random_forest_run](https://github.com/automl/random_forest_run/blob/main/.github/workflows/release.yml)), but I personally haven't played around with it much.

**Comment by Mic92** [comment]
We have an aarch64 builder via hercules ci, if you find a way to use its artifacts in a github action, than this solves the issue.

**Comment by zowoq** [comment]
I think we should be able to use hercules to publish the artifacts.

https://github.com/hercules-ci/hercules-ci-agent/releases/tag/hercules-ci-agent-0.9.8
https://github.com/hercules-ci/hercules-ci-effects/blob/master/effects/modules/git-auth-gh.nix

Since 0.9.8 hercules can get a token directly from github and effects can configure `gh` to use the token.

**Comment by Mic92** [comment]
aarch64 support has been added: https://github.com/nix-community/nixos-images/blob/fcbf0b7c6c1f23ad97f2fed4f00f8d9e7181c22f/.github/workflows/build.yml#L17
