### ISSUE TITLE
root authorized_keys are not copied

### ISSUE THREAD

**Issue by bluepython508** [nix-community/nixos-images#121]
After running the `kexec` step from nixos-anywhere, the `/root/.ssh/authorized_keys` file is empty due to [this line](https://github.com/nix-community/nixos-images/blob/f98b4775fa665c1e14055a938a744172c8e081c3/nix/kexec-installer/kexec-run.sh#L24), as the ssh keys listed are not surrounded with parentheses. This appears to have been introduced in #23, but with no explanation. Why are only ssh keys that are surrounded by parentheses permitted? (This doesn't appear to be valid syntax in my sshd, at least)

**Comment by Mic92** [comment]
Debian disables the root login for keys using some force-command, so if we take the key than we can no longer login.

**Comment by Mic92** [comment]
What does your key looks like?

**Comment by Mic92** [comment]
Ok. Those keys should be copied. Do you have logs of nixos-anywhere?

**Comment by Mic92** [comment]
Ok. You can also pass --debug to make the output more verbose.

**Comment by dzmitry-lahoda** [comment]
I used kexec approach with fresh hetzner ubuntu machine. Got the issue.

**Comment by dzmitry-lahoda** [comment]
I do not see NUL (i am not expert, tried to clean up via nano if any)

```
root@rescue ~ # cat .ssh/authorized_keys 
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBETcP7NOsUaE/jHYqJ8rZk3dnX1Ff4+cIZQOsV45G8hHcE+15X/4xuctcnMYa1HICbde7rPJNqmDgsF2Ki5lklo=
```

**Comment by dzmitry-lahoda** [comment]
I see. regex  kind of does no friends other `-t` keys for ssh,

trying default
