### ISSUE TITLE
Support  ecdsa | ecdsa-sk | ed25519 | ed25519-sk ssh keys

### ISSUE THREAD

**Issue by dzmitry-lahoda** [nix-community/nixos-images#133]
When I used non rsa keys, running command to execute nixos kexec fails to detect ssh authorized keys.

**Comment by Mic92** [comment]
Our tests uses ed25519 actually: https://github.com/nix-community/nixos-images/blob/c4c73bce65306a1e747684dd0d4bcf0ab2779585/nix/kexec-installer/test.nix#L128

**Comment by Mic92** [comment]
https://github.com/nix-community/nixos-images/blob/c4c73bce65306a1e747684dd0d4bcf0ab2779585/nix/kexec-installer/kexec-run.sh#L24

**Comment by dzmitry-lahoda** [comment]
hm, i tried to times on hetzner from rescue. key worked as used to login to original or and rescue, but 
for kexec nixoa.  when i switched to rsa it worked.
