### ISSUE TITLE
reconsider default to zfs

### ISSUE THREAD

**Issue by sielicki** [nix-community/nixos-images#158]
when looking at replacing [broken kexec nixos-generators](https://github.com/nix-community/nixos-generators/tree/master/formats-broken) with this, was surprised to see zfs a default. Would prefer to see this use `boot.kernelPackages = lib.mkDefault pkgs.linuxPackages_testing;` so that it can more-aggressively target new platforms.

**Comment by Mic92** [comment]
We already use the latest kernel that supports zfs (6.6 just now, which is the latest release). We need zfs in many places, so this is not an option.
