### ISSUE TITLE
zvol udev rules not included in noninteractive kexec tarball

### ISSUE THREAD

**Issue by nbdd0121** [nix-community/nixos-images#162]
The image does not contain zvol udev rules, so if nixos-anywhere tries to install disko configuration with zvol, it will stuck waiting for /dev/zvol to come online.

The udev rule is added to normal nixos system here:

https://github.com/NixOS/nixpkgs/blob/0d963f99ef3d73acacb1a017dbe49a40ce86cba0/nixos/modules/tasks/filesystems/zfs.nix#L725

**Comment by Mic92** [comment]
Fixed in https://github.com/nix-community/nixos-images/pull/163
