### ISSUE TITLE
ipv4 route via ipv6

### ISSUE THREAD

**Issue by name-snrl** [nix-community/nixos-images#230]
I tried to deploy NixOS using `nixos-anywhere` and ran into a problem. In my case, routing for ipv4 is configured via ipv6, it looks like this:

```bash
~/kexec# ./ip -4 route                   
default via inet6 fe80::1 dev ens10f0np0 
```

script checks that `protocol` is `kernel` and drops the route. Is there any solution for this?

**Comment by Mic92** [comment]
Any idea what proto is actually set to if not specified? We can probably also pass through routes if proto is set to "static" or not set at all. The only thing we want to filter out is dhcp most of the time.

**Comment by name-snrl** [comment]
> Any idea what proto is actually set to if not specified?

Oops, my bad, I said it was set to `kernel` but that was for docker. I think we just need to add an extra check for `family`?

```bash
ip -4 --json route | jq
[
  {
    "dst": "default",
    "via": {
      "family": "inet6",
      "host": "fe80::1"
    },
    "dev": "ens10f0np0",
    "flags": []
  },
  {
    "dst": "172.17.0.0/16",
    "dev": "docker0",
    "protocol": "kernel",
    "scope": "link",
    "prefsrc": "172.17.0.1",
    "flags": [
      "linkdown"
    ]
  }
]
```

**Comment by Mic92** [comment]
Looks like we would than also need to parse "via", "host" here:

https://github.com/nix-community/nixos-images/blob/f267906ba610b2e29f3f45ab45a0669e28c407ef/nix/kexec-installer/restore_routes.py#L65

Just now we skip everything that has no Gateway.
Could be also extended in our test suite to avoid future regressions: https://github.com/nix-community/nixos-images/blob/f267906ba610b2e29f3f45ab45a0669e28c407ef/nix/kexec-installer/test.nix#L155
Pull requests are welcome.

**Comment by name-snrl** [comment]
> Pull requests are welcome.

At the moment I have already deployed one machine and am in the process of configuring it, but the plan is to deploy a cluster in the future, and if no one has fixed this by then - I will do so.
