### ISSUE TITLE
Point to latest release

### ISSUE THREAD

**Issue by moritztim** [nix-community/nixos-images#305]
Shouldn't the download link in the readme curl command point to the latest release?

**Comment by Mic92** [comment]
Feel free to change the link

**Comment by moritztim** [comment]
Sure, but I'm wondering why it's apparently recommended to use an outdated installer image? Why not have the readme point to `latest` instead? Or did you mean to imply I should make a pull request to change that?

**Comment by Mic92** [comment]
Yes. Please make a pull request. We are pointing to the unstable installer right now, no?

**Comment by moritztim** [comment]
Yes. The one from [this release](https://github.com/nix-community/nixos-images/releases/tag/nixos-unstable)
