### ISSUE TITLE
22.11 release ipxe script contains 21.11?

### ISSUE THREAD

**Issue by gpl** [nix-community/nixos-images#56]
When attempting to use 22.11 ipxe, I seem to be booting into a NixOS 21.11 installer, not 22.11.

I noticed that in this file, the nixos-2211 url seems to be pointing 21.11, not 22.11 -- https://github.com/nix-community/nixos-images/blob/main/flake.nix#LL5

**Comment by Mic92** [comment]
fixed. Thanks!
